const fs = require('fs');
const path = require('path');
const resourcesDir = path.join('C:', 'Users', 'kogli', 'Desktop', 'Projetos', 'Windows', 'DesktopCommandCenter-Enterprise', 'Community', 'src', 'DesktopCommandCenter.UI', 'Resources');

const translations = {
    "pt-BR": {
        "Dashboard_MetricTools": "Ferramentas",
        "Dashboard_MetricNotes": "Notas salvas",
        "Dashboard_MetricClip": "No Clipboard",
        "Dashboard_MetricPlan": "Plano atual",
        "Dashboard_SectionComm": "Ferramentas da Comunidade",
        "Dashboard_SectionPro": "Recursos PRO (IA & Automação)",
        "Dashboard_ToolColorTitle": "Seletor de Cores",
        "Dashboard_ToolColorDesc": "Captura cores da tela",
        "Dashboard_ToolClipTitle": "Clipboard",
        "Dashboard_ToolClipDesc": "Histórico de cópias",
        "Dashboard_ToolNotesTitle": "Notas",
        "Dashboard_ToolNotesDesc": "Anotações rápidas",
        "Dashboard_ToolCaptureTitle": "Captura de Tela",
        "Dashboard_ToolCaptureDesc": "Tirar prints da tela",
        "Dashboard_ToolAwakeTitle": "Modo Ativo",
        "Dashboard_ToolAwakeDesc": "Mantém o PC acordado",
        "Dashboard_ToolTopTitle": "Sempre no Topo",
        "Dashboard_ToolTopDesc": "Fixa janelas na frente",
        "Dashboard_ToolTransTitle": "Tradutor",
        "Dashboard_ToolTransDesc": "Tradução instantânea",
        "Dashboard_ToolTimerTitle": "Temporizador",
        "Dashboard_ToolTimerDesc": "Cronômetro e timer",
        "Dashboard_ToolUpdateTitle": "Update Center",
        "Dashboard_ToolUpdateDesc": "Atualizações de apps",
        "Dashboard_ToolSearchTitle": "Pesquisa Universal",
        "Dashboard_ToolSearchDesc": "Busca em tudo",
        "Dashboard_ToolPalleteTitle": "Paleta de Comandos",
        "Dashboard_ToolPalleteDesc": "Comandos CLI rápidos",
        "Dashboard_ToolShellTitle": "FutureShell",
        "Dashboard_ToolShellDesc": "Terminal Independente",
        "Dashboard_Pro1Title": "ChatFT",
        "Dashboard_Pro1Desc": "Transcrição e chat offline",
        "Dashboard_Pro2Title": "Automações",
        "Dashboard_Pro2Desc": "Workflows automatizados",
        "Dashboard_Pro3Title": "Cloud Sync",
        "Dashboard_Pro3Desc": "Sincronize notas e dados",
        "Dashboard_Pro4Title": "Perfis",
        "Dashboard_Pro4Desc": "Múltiplos perfis de uso",
        "Dashboard_PromptsTitle": "Prompts de IA",
        "Dashboard_PromptsDesc": "Biblioteca de prompts",
        "Dashboard_BtnDoc": "Documentação",
        "Dashboard_BtnGitHub": "Repositório GitHub",
        "Dashboard_BtnAbout": "Sobre o Projeto",
        "Dashboard_BtnBugReport": "Reportar Bug",
        "Dashboard_BtnUpgradePro": "🚀 Conhecer o PRO",
        "Dashboard_BtnStripe": "💳 Checkout Stripe",
        "Dashboard_StripeMonthly": "Assinatura Mensal | R$ 39,90",
        "Dashboard_StripeYearly": "Assinatura Anual | R$ 429,90",
        "Dashboard_Copyright": "© 2026 Foreign Technologies®. All rights reserved"
    },
    "en-US": {
        "Dashboard_MetricTools": "Tools",
        "Dashboard_MetricNotes": "Saved Notes",
        "Dashboard_MetricClip": "On Clipboard",
        "Dashboard_MetricPlan": "Current Plan",
        "Dashboard_SectionComm": "Community Tools",
        "Dashboard_SectionPro": "PRO Features (AI & Automation)",
        "Dashboard_ToolColorTitle": "Color Picker",
        "Dashboard_ToolColorDesc": "Capture colors from screen",
        "Dashboard_ToolClipTitle": "Clipboard",
        "Dashboard_ToolClipDesc": "Copy history",
        "Dashboard_ToolNotesTitle": "Notes",
        "Dashboard_ToolNotesDesc": "Quick annotations",
        "Dashboard_ToolCaptureTitle": "Screen Capture",
        "Dashboard_ToolCaptureDesc": "Take screenshots",
        "Dashboard_ToolAwakeTitle": "Awake Mode",
        "Dashboard_ToolAwakeDesc": "Keeps PC awake",
        "Dashboard_ToolTopTitle": "Always On Top",
        "Dashboard_ToolTopDesc": "Fixes windows in front",
        "Dashboard_ToolTransTitle": "Translator",
        "Dashboard_ToolTransDesc": "Instant translation",
        "Dashboard_ToolTimerTitle": "Timer",
        "Dashboard_ToolTimerDesc": "Stopwatch and timer",
        "Dashboard_ToolUpdateTitle": "Update Center",
        "Dashboard_ToolUpdateDesc": "App updates",
        "Dashboard_ToolSearchTitle": "Universal Search",
        "Dashboard_ToolSearchDesc": "Search everything",
        "Dashboard_ToolPalleteTitle": "Command Palette",
        "Dashboard_ToolPalleteDesc": "Quick CLI commands",
        "Dashboard_ToolShellTitle": "FutureShell",
        "Dashboard_ToolShellDesc": "Independent Terminal",
        "Dashboard_Pro1Title": "ChatFT",
        "Dashboard_Pro1Desc": "Transcription and offline chat",
        "Dashboard_Pro2Title": "Automations",
        "Dashboard_Pro2Desc": "Automated workflows",
        "Dashboard_Pro3Title": "Cloud Sync",
        "Dashboard_Pro3Desc": "Sync notes and data",
        "Dashboard_Pro4Title": "Profiles",
        "Dashboard_Pro4Desc": "Multiple usage profiles",
        "Dashboard_PromptsTitle": "AI Prompts",
        "Dashboard_PromptsDesc": "Prompt library",
        "Dashboard_BtnDoc": "Documentation",
        "Dashboard_BtnGitHub": "GitHub Repository",
        "Dashboard_BtnAbout": "About the Project",
        "Dashboard_BtnBugReport": "Report Bug",
        "Dashboard_BtnUpgradePro": "🚀 Explore PRO",
        "Dashboard_BtnStripe": "💳 Stripe Checkout",
        "Dashboard_StripeMonthly": "Monthly Subscription | $9.99/mo",
        "Dashboard_StripeYearly": "Annual Subscription | $99.90/yr",
        "Dashboard_Copyright": "© 2026 Foreign Technologies®. All rights reserved"
    },
    "es-ES": {
        "Dashboard_MetricTools": "Herramientas",
        "Dashboard_MetricNotes": "Notas guardadas",
        "Dashboard_MetricClip": "En Portapapeles",
        "Dashboard_MetricPlan": "Plan actual",
        "Dashboard_SectionComm": "Herramientas de la Comunidad",
        "Dashboard_SectionPro": "Recursos PRO (IA & Automatización)",
        "Dashboard_ToolColorTitle": "Selector de Colores",
        "Dashboard_ToolColorDesc": "Captura colores de la pantalla",
        "Dashboard_ToolClipTitle": "Portapapeles",
        "Dashboard_ToolClipDesc": "Historial de copias",
        "Dashboard_ToolNotesTitle": "Notas",
        "Dashboard_ToolNotesDesc": "Anotaciones rápidas",
        "Dashboard_ToolCaptureTitle": "Captura de Pantalla",
        "Dashboard_ToolCaptureDesc": "Tomar capturas",
        "Dashboard_ToolAwakeTitle": "Modo Activo",
        "Dashboard_ToolAwakeDesc": "Mantiene el PC despierto",
        "Dashboard_ToolTopTitle": "Siempre Visible",
        "Dashboard_ToolTopDesc": "Fija ventanas al frente",
        "Dashboard_ToolTransTitle": "Traductor",
        "Dashboard_ToolTransDesc": "Traducción instantánea",
        "Dashboard_ToolTimerTitle": "Temporizador",
        "Dashboard_ToolTimerDesc": "Cronómetro y temporizador",
        "Dashboard_ToolUpdateTitle": "Update Center",
        "Dashboard_ToolUpdateDesc": "Actualizaciones de apps",
        "Dashboard_ToolSearchTitle": "Búsqueda Universal",
        "Dashboard_ToolSearchDesc": "Busca en todo",
        "Dashboard_ToolPalleteTitle": "Paleta de Comandos",
        "Dashboard_ToolPalleteDesc": "Comandos CLI rápidos",
        "Dashboard_ToolShellTitle": "FutureShell",
        "Dashboard_ToolShellDesc": "Terminal Independiente",
        "Dashboard_Pro1Title": "ChatFT",
        "Dashboard_Pro1Desc": "Transcripción y chat sin conexión",
        "Dashboard_Pro2Title": "Automatizaciones",
        "Dashboard_Pro2Desc": "Flujos de trabajo automatizados",
        "Dashboard_Pro3Title": "Sincronización en Nube",
        "Dashboard_Pro3Desc": "Sincroniza notas y datos",
        "Dashboard_Pro4Title": "Perfiles",
        "Dashboard_Pro4Desc": "Múltiples perfiles de uso",
        "Dashboard_PromptsTitle": "Prompts de IA",
        "Dashboard_PromptsDesc": "Biblioteca de prompts",
        "Dashboard_BtnDoc": "Documentación",
        "Dashboard_BtnGitHub": "Repositorio GitHub",
        "Dashboard_BtnAbout": "Sobre el Proyecto",
        "Dashboard_BtnBugReport": "Reportar Bug",
        "Dashboard_BtnUpgradePro": "🚀 Conocer el PRO",
        "Dashboard_BtnStripe": "💳 Checkout Stripe",
        "Dashboard_StripeMonthly": "Suscripción Mensual | $ 9,99/mes",
        "Dashboard_StripeYearly": "Suscripción Anual | $ 99,90/año",
        "Dashboard_Copyright": "© 2026 Foreign Technologies®. All rights reserved"
    }
};

for (const [lang, newKeys] of Object.entries(translations)) {
    const filePath = path.join(resourcesDir, lang + '.json');
    if (fs.existsSync(filePath)) {
        let dict = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        dict = { ...dict, ...newKeys };
        fs.writeFileSync(filePath, JSON.stringify(dict, null, 2), 'utf8');
    }
}
console.log('Dashboard JSON updated');
