const fs = require('fs');
const path = require('path');
const viewsDir = path.join('C:', 'Users', 'kogli', 'Desktop', 'Projetos', 'Windows', 'DesktopCommandCenter-Enterprise', 'Community', 'src', 'DesktopCommandCenter.UI', 'Views');
const resourcesDir = path.join('C:', 'Users', 'kogli', 'Desktop', 'Projetos', 'Windows', 'DesktopCommandCenter-Enterprise', 'Community', 'src', 'DesktopCommandCenter.UI', 'Resources');

// All translations for all remaining pages
const translations = {
  "pt-BR": {
    "BugReport_Title": "Reportar um Problema",
    "BugReport_BtnSend": "Enviar Reporte",
    "BugReport_BtnCancel": "Cancelar",
    "BugReport_Desc": "Obrigado por ajudar a melhorar o DCC! Por favor, descreva o problema que você encontrou com o máximo de detalhes possível.",
    "BugReport_InputTitle": "Título do Problema",
    "BugReport_InputTitle_Placeholder": "Ex: App fecha ao abrir as anotações",
    "BugReport_InputDesc": "Descrição Detalhada",
    "BugReport_InputDesc_Placeholder": "Passos para reproduzir o erro, o que era esperado vs o que aconteceu...",
    "BugReport_AttachTitle": "Anexar um Print (Opcional)",
    "BugReport_NoFile": "Nenhum arquivo anexado",
    "BugReport_BtnBrowse": "Procurar...",
    "Captura_PageTitle": "Captura de Tela",
    "Captura_SubTitle": "Estúdio de Captura",
    "Captura_Desc": "Selecione abaixo para iniciar a ferramenta de captura de tela inteligente do Windows e salvar imagens diretamente no seu Clipboard.",
    "Captura_BtnNew": "📸 Nova Captura",
    "Clipboard_PageTitle": "Smart Clipboard",
    "Clipboard_BtnClear": "Limpar Histórico",
    "Clipboard_ItemCopy": "Copiar novamente",
    "Clipboard_ItemDelete": "Excluir",
    "ColorPicker_PageTitle": "Color Picker",
    "ColorPicker_HexLabel": "HEX",
    "ColorPicker_BtnCopyHex": "Copiar HEX",
    "ColorPicker_RgbLabel": "RGB",
    "ColorPicker_BtnCopyRgb": "Copiar RGB",
    "ColorPicker_EyedropperBtn": "Ativar Conta-gotas (Mouse)",
    "ColorPicker_EyedropperDesc": "Mova o mouse pela tela para capturar cores de qualquer janela. Clique em copiar para salvar.",
    "ComingSoon_Title": "Em Breve!",
    "ComingSoon_Desc": "Estamos construindo este módulo para você.",
    "Notes_PageTitle": "Notas Rápidas",
    "Notes_BtnNew": "Nova Nota",
    "OOBE_Title": "Bem-vindo ao Desktop Command Center!",
    "OOBE_BtnContinue": "Continuar",
    "OOBE_ThemeLabel": "Antes de começarmos, escolha o seu tema preferido:",
    "OOBE_ThemeLight": "Claro",
    "OOBE_ThemeDark": "Escuro",
    "OOBE_ThemeSystem": "Padrão do Sistema (Contraste)",
    "OOBE_ThemeNote": "Você poderá alterar isso nas Configurações posteriormente.",
    "Search_PageTitle": "Pesquisa Universal Avançada",
    "Search_Placeholder": "Pesquise apps, arquivos, configs ou digite > para comandos e = para cálculos...",
    "Search_BtnOpen": "Abrir / Executar",
    "Search_BtnSendAI": "Enviar para IA",
    "ProcessMgr_PageTitle": "Gerenciador de Processos Avançado",
    "ProcessMgr_SearchPlaceholder": "Pesquisar processos por nome...",
    "ProcessMgr_ColName": "Nome do Processo",
    "ProcessMgr_ColPid": "PID",
    "ProcessMgr_ColCpu": "CPU (%)",
    "ProcessMgr_ColRam": "RAM (MB)",
    "ProcessMgr_ColStatus": "Status",
    "ProcessMgr_BtnKillTree": "Encerrar Árvore de Processos",
    "ProcessMgr_StatusOrphan": "Órfão",
    "Prompts_PageTitle": "Biblioteca de Prompts",
    "Prompts_BtnCopy": "Copiar",
    "Prompts_BtnEdit": "Editar",
    "Prompts_BtnDelete": "Excluir",
    "Prompts_EmptyTitle": "Nenhum prompt salvo ainda.",
    "Prompts_EmptyDesc": "Crie um novo prompt usando o formulário à direita.",
    "Prompts_FormTitle": "Título",
    "Prompts_FormTitle_Placeholder": "Ex: Revisar Código",
    "Prompts_FormCategory": "Categoria",
    "Prompts_FormCategory_Placeholder": "Ex: Programação",
    "Prompts_FormContent": "Conteúdo do Prompt",
    "Prompts_FormContent_Placeholder": "Por favor, revise o código abaixo...",
    "Prompts_BtnSave": "Salvar",
    "Prompts_BtnCancel": "Cancelar",
    "Temporizador_PageTitle": "Temporizador (Pomodoro)",
    "Temporizador_Years": "Anos",
    "Temporizador_Months": "Meses",
    "Temporizador_Days": "Dias",
    "Temporizador_Hours": "Horas",
    "Temporizador_Minutes": "Minutos",
    "Temporizador_Seconds": "Segundos",
    "Temporizador_Ms": "Milissegundos",
    "Temporizador_BtnStart": "Iniciar",
    "Temporizador_BtnPause": "Pausar",
    "Temporizador_BtnReset": "Resetar"
  },
  "en-US": {
    "BugReport_Title": "Report a Problem",
    "BugReport_BtnSend": "Send Report",
    "BugReport_BtnCancel": "Cancel",
    "BugReport_Desc": "Thank you for helping improve DCC! Please describe the issue you encountered with as much detail as possible.",
    "BugReport_InputTitle": "Problem Title",
    "BugReport_InputTitle_Placeholder": "Ex: App closes when opening notes",
    "BugReport_InputDesc": "Detailed Description",
    "BugReport_InputDesc_Placeholder": "Steps to reproduce the error, what was expected vs what happened...",
    "BugReport_AttachTitle": "Attach a Screenshot (Optional)",
    "BugReport_NoFile": "No file attached",
    "BugReport_BtnBrowse": "Browse...",
    "Captura_PageTitle": "Screen Capture",
    "Captura_SubTitle": "Capture Studio",
    "Captura_Desc": "Select below to launch the Windows smart screenshot tool and save images directly to your Clipboard.",
    "Captura_BtnNew": "📸 New Capture",
    "Clipboard_PageTitle": "Smart Clipboard",
    "Clipboard_BtnClear": "Clear History",
    "Clipboard_ItemCopy": "Copy again",
    "Clipboard_ItemDelete": "Delete",
    "ColorPicker_PageTitle": "Color Picker",
    "ColorPicker_HexLabel": "HEX",
    "ColorPicker_BtnCopyHex": "Copy HEX",
    "ColorPicker_RgbLabel": "RGB",
    "ColorPicker_BtnCopyRgb": "Copy RGB",
    "ColorPicker_EyedropperBtn": "Activate Eyedropper (Mouse)",
    "ColorPicker_EyedropperDesc": "Move the mouse over the screen to capture colors from any window. Click copy to save.",
    "ComingSoon_Title": "Coming Soon!",
    "ComingSoon_Desc": "We are building this module for you.",
    "Notes_PageTitle": "Quick Notes",
    "Notes_BtnNew": "New Note",
    "OOBE_Title": "Welcome to Desktop Command Center!",
    "OOBE_BtnContinue": "Continue",
    "OOBE_ThemeLabel": "Before we start, choose your preferred theme:",
    "OOBE_ThemeLight": "Light",
    "OOBE_ThemeDark": "Dark",
    "OOBE_ThemeSystem": "System Default (Contrast)",
    "OOBE_ThemeNote": "You can change this in Settings later.",
    "Search_PageTitle": "Advanced Universal Search",
    "Search_Placeholder": "Search apps, files, configs or type > for commands and = for calculations...",
    "Search_BtnOpen": "Open / Run",
    "Search_BtnSendAI": "Send to AI",
    "ProcessMgr_PageTitle": "Advanced Process Manager",
    "ProcessMgr_SearchPlaceholder": "Search processes by name...",
    "ProcessMgr_ColName": "Process Name",
    "ProcessMgr_ColPid": "PID",
    "ProcessMgr_ColCpu": "CPU (%)",
    "ProcessMgr_ColRam": "RAM (MB)",
    "ProcessMgr_ColStatus": "Status",
    "ProcessMgr_BtnKillTree": "Kill Process Tree",
    "ProcessMgr_StatusOrphan": "Orphan",
    "Prompts_PageTitle": "Prompt Library",
    "Prompts_BtnCopy": "Copy",
    "Prompts_BtnEdit": "Edit",
    "Prompts_BtnDelete": "Delete",
    "Prompts_EmptyTitle": "No prompts saved yet.",
    "Prompts_EmptyDesc": "Create a new prompt using the form on the right.",
    "Prompts_FormTitle": "Title",
    "Prompts_FormTitle_Placeholder": "Ex: Review Code",
    "Prompts_FormCategory": "Category",
    "Prompts_FormCategory_Placeholder": "Ex: Programming",
    "Prompts_FormContent": "Prompt Content",
    "Prompts_FormContent_Placeholder": "Please review the code below...",
    "Prompts_BtnSave": "Save",
    "Prompts_BtnCancel": "Cancel",
    "Temporizador_PageTitle": "Timer (Pomodoro)",
    "Temporizador_Years": "Years",
    "Temporizador_Months": "Months",
    "Temporizador_Days": "Days",
    "Temporizador_Hours": "Hours",
    "Temporizador_Minutes": "Minutes",
    "Temporizador_Seconds": "Seconds",
    "Temporizador_Ms": "Milliseconds",
    "Temporizador_BtnStart": "Start",
    "Temporizador_BtnPause": "Pause",
    "Temporizador_BtnReset": "Reset"
  },
  "es-ES": {
    "BugReport_Title": "Reportar un Problema",
    "BugReport_BtnSend": "Enviar Reporte",
    "BugReport_BtnCancel": "Cancelar",
    "BugReport_Desc": "¡Gracias por ayudar a mejorar DCC! Por favor, describe el problema que encontraste con el mayor detalle posible.",
    "BugReport_InputTitle": "Título del Problema",
    "BugReport_InputTitle_Placeholder": "Ej: La app se cierra al abrir las notas",
    "BugReport_InputDesc": "Descripción Detallada",
    "BugReport_InputDesc_Placeholder": "Pasos para reproducir el error, qué se esperaba vs qué ocurrió...",
    "BugReport_AttachTitle": "Adjuntar una Captura (Opcional)",
    "BugReport_NoFile": "Ningún archivo adjunto",
    "BugReport_BtnBrowse": "Buscar...",
    "Captura_PageTitle": "Captura de Pantalla",
    "Captura_SubTitle": "Estudio de Captura",
    "Captura_Desc": "Selecciona a continuación para iniciar la herramienta de captura de pantalla de Windows y guardar imágenes directamente en tu Portapapeles.",
    "Captura_BtnNew": "📸 Nueva Captura",
    "Clipboard_PageTitle": "Portapapeles Inteligente",
    "Clipboard_BtnClear": "Limpiar Historial",
    "Clipboard_ItemCopy": "Copiar de nuevo",
    "Clipboard_ItemDelete": "Eliminar",
    "ColorPicker_PageTitle": "Selector de Color",
    "ColorPicker_HexLabel": "HEX",
    "ColorPicker_BtnCopyHex": "Copiar HEX",
    "ColorPicker_RgbLabel": "RGB",
    "ColorPicker_BtnCopyRgb": "Copiar RGB",
    "ColorPicker_EyedropperBtn": "Activar Cuentagotas (Ratón)",
    "ColorPicker_EyedropperDesc": "Mueve el ratón por la pantalla para capturar colores de cualquier ventana. Haz clic en copiar para guardar.",
    "ComingSoon_Title": "¡Próximamente!",
    "ComingSoon_Desc": "Estamos construyendo este módulo para ti.",
    "Notes_PageTitle": "Notas Rápidas",
    "Notes_BtnNew": "Nueva Nota",
    "OOBE_Title": "¡Bienvenido a Desktop Command Center!",
    "OOBE_BtnContinue": "Continuar",
    "OOBE_ThemeLabel": "Antes de empezar, elige tu tema preferido:",
    "OOBE_ThemeLight": "Claro",
    "OOBE_ThemeDark": "Oscuro",
    "OOBE_ThemeSystem": "Predeterminado del Sistema (Contraste)",
    "OOBE_ThemeNote": "Puedes cambiarlo en Configuración más adelante.",
    "Search_PageTitle": "Búsqueda Universal Avanzada",
    "Search_Placeholder": "Busca apps, archivos, configs o escribe > para comandos y = para cálculos...",
    "Search_BtnOpen": "Abrir / Ejecutar",
    "Search_BtnSendAI": "Enviar a IA",
    "ProcessMgr_PageTitle": "Administrador de Procesos Avanzado",
    "ProcessMgr_SearchPlaceholder": "Buscar procesos por nombre...",
    "ProcessMgr_ColName": "Nombre del Proceso",
    "ProcessMgr_ColPid": "PID",
    "ProcessMgr_ColCpu": "CPU (%)",
    "ProcessMgr_ColRam": "RAM (MB)",
    "ProcessMgr_ColStatus": "Estado",
    "ProcessMgr_BtnKillTree": "Terminar Árbol de Procesos",
    "ProcessMgr_StatusOrphan": "Huérfano",
    "Prompts_PageTitle": "Biblioteca de Prompts",
    "Prompts_BtnCopy": "Copiar",
    "Prompts_BtnEdit": "Editar",
    "Prompts_BtnDelete": "Eliminar",
    "Prompts_EmptyTitle": "Aún no hay prompts guardados.",
    "Prompts_EmptyDesc": "Crea un nuevo prompt usando el formulario de la derecha.",
    "Prompts_FormTitle": "Título",
    "Prompts_FormTitle_Placeholder": "Ej: Revisar Código",
    "Prompts_FormCategory": "Categoría",
    "Prompts_FormCategory_Placeholder": "Ej: Programación",
    "Prompts_FormContent": "Contenido del Prompt",
    "Prompts_FormContent_Placeholder": "Por favor, revisa el código a continuación...",
    "Prompts_BtnSave": "Guardar",
    "Prompts_BtnCancel": "Cancelar",
    "Temporizador_PageTitle": "Temporizador (Pomodoro)",
    "Temporizador_Years": "Años",
    "Temporizador_Months": "Meses",
    "Temporizador_Days": "Días",
    "Temporizador_Hours": "Horas",
    "Temporizador_Minutes": "Minutos",
    "Temporizador_Seconds": "Segundos",
    "Temporizador_Ms": "Milisegundos",
    "Temporizador_BtnStart": "Iniciar",
    "Temporizador_BtnPause": "Pausar",
    "Temporizador_BtnReset": "Reiniciar"
  }
};

for (const [lang, newKeys] of Object.entries(translations)) {
  const filePath = path.join(resourcesDir, lang + '.json');
  if (fs.existsSync(filePath)) {
    let dict = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    dict = { ...dict, ...newKeys };
    fs.writeFileSync(filePath, JSON.stringify(dict, null, 2), 'utf8');
    console.log('Updated', lang);
  }
}
